version: "3.2"
services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"

  rabbitmq:
    image: oteljava/rabbitmq:3-management-alpine
    build: 
      context: "./infrastructure/rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:latest

  prometheus:
    image: prom/prometheus
    volumes:
      - ./infrastructure/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
      
  worker1: 
    image: oteljava/worker1:v2
    container_name: worker1
    build: 
      context: "./worker1"
    environment:
      - AGENTTYPE
      - OTEL_LOG_LEVEL
      - OTEL_JAVAAGENT_DEBUG
      - OTEL_AZ_MONITOR_CONNECTION
      - OTEL_TRACES_EXPORTER
      - OTEL_METRICS_EXPORTER
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      - OTEL_EXPORTER_PROMETHEUS_HOST=worker1
      - OTEL_EXPORTER_JAEGER_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES=service.name=worker1
    depends_on:
      - redis
      - rabbitmq
      - jaeger
    ports:
      - 9464:9464

  worker2: 
    image: oteljava/worker2:v2
    container_name: worker2
    build: 
      context: "./worker2"
    environment:
      - AGENTTYPE
      - OTEL_LOG_LEVEL
      - OTEL_JAVAAGENT_DEBUG
      - OTEL_AZ_MONITOR_CONNECTION
      - OTEL_TRACES_EXPORTER
      - OTEL_METRICS_EXPORTER
      - OTEL_EXPORTER_PROMETHEUS_PORT=9465
      - OTEL_EXPORTER_PROMETHEUS_HOST=worker2
      - OTEL_EXPORTER_JAEGER_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES=service.name=worker2
    depends_on:
      - redis
      - rabbitmq
      - jaeger
    ports:
      - 9465:9465

  client:
    image: oteljava/client:v2
    container_name: client
    build:
      context: "./client"
    environment: 
      - AGENTTYPE
      - OTEL_LOG_LEVEL
      - OTEL_JAVAAGENT_DEBUG
      - OTEL_AZ_MONITOR_CONNECTION
      - OTEL_TRACES_EXPORTER
      - OTEL_METRICS_EXPORTER
      - OTEL_EXPORTER_PROMETHEUS_PORT=9466
      - OTEL_EXPORTER_PROMETHEUS_HOST=client
      - OTEL_EXPORTER_JAEGER_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES=service.name=otelclient
    depends_on:
      - rabbitmq
      - jaeger
      - worker1
      - worker2
    ports:
      - 9466:9466

